export interface HttpResponse<T> {
    htmlCode: number;
    status: string;
    result: {
        message: string;
        data?: T;
        errorInfo?: any;
    }
}

export const HTMLCodes = {
    SUCCESS: 200,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    SERVER_ERROR: 500,
    NOT_IMPLEMENTED: 501,
}

export const ERROR_STATUS = {
     SUCCESS_STATUS: 'SUCCESS',
     NOT_AUTH_REFRESH_STATUS: 'NOT_AUTH_REFRESH',
     NOT_FOUND_STATUS: 'NOT_FOUND',
     MALFORMED_TOKEN_STATUS: 'MALFORMED_TOKEN',
     MISSING_AUTH_STATUS: 'MISSING_AUTHORIZATION_HEADER',
     MISSING_API_KEY_STATUS: 'MISSING_API_KEY_HEADER',
     EXPIRED_TOKEN_STATUS: 'EXPIRED_TOKEN',
     WRONG_TOKEN_TYPE_STATUS: 'WRONG_TOKEN_TYPE',
     INVALID_APP_TOKEN_STATUS: 'INVALID_APP_TOKEN',
     VALIDATION_ERROR_STATUS: 'VALIDATION_ERROR',
     ALREADY_EXISTS_STATUS: 'ALREADY_EXISTS',
     ALREADY_ACTIVE_STATUS: 'ALREADY_ACTIVE',
     INACTIVE_USER_STATUS: 'INACTIVE_USER',
     UNAUTHORIZED_STATUS: 'UNAUTHORIZED',
     INVALID_CREDENTIALS_STATUS: 'INVALID_CREDENTIALS',
     SERVER_ERROR_STATUS: 'SERVER_ERROR',
     TOO_MUCH_DATA_STATUS: 'TOO_MUCH_DATA_ERROR',
     TOO_LESS_DATA_STATUS: 'TOO_LESS_DATA_ERROR',
     INTEGRITY_DATA_STATUS: 'INTEGRITY_DATA_ERROR',
     RESOURCE_ACCESS_DENIED_STATUS: 'RESOURCE_ACCESS_DENIED',
     USER_PERMISSION_DENIED_STATUS: 'USER_PERMISSION_DENIED',
     APP_PERMISSION_DENIED_STATUS: 'APP_PERMISSION_DENIED',
     SCOPE_PERMISSION_DENIED_STATUS: 'SCOPE_DENIED',
     DATABASE_ACCESS_DENIED_STATUS: 'DATABASE_ACCESS_DENIED',
     NOT_IMPLEMENTED_STATUS: 'NOT_IMPLEMENTED',
     USER_TEMPORARILY_BLOCKED_STATUS: 'USER_TEPORARILY_BLOCKED',
     USER_BLOCKED_STATUS: 'USER_BLOCKED',
     LOGIN_DENIED_STATUS: 'LOGIN_DENIED',
     MISSING_DATA_STATUS: 'MISSING_DATA',
     LIMIT_REACHED_STATUS: 'LIMIT_REACHED',
}